name: "docker-build"
description: "docker build"
inputs:
    username:
        required: true
    password:
        required: true
    imagename:
        required: true
    tagname:
        default: "latest"
runs:
    using: "composite"
    steps:
        - name: setup env
          run: echo "_username=${OWNER,,}" >> $GITHUB_ENV
          env:
              OWNER: ${{ inputs.username }}
          shell: bash
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ env._username }}
              password: ${{ inputs.password }}
        - name: build
          run: docker build . --tag ghcr.io/${{ env._username }}/${{ inputs.imagename }}:${{ inputs.tagname }}
          shell: bash
        - name: Build and push Docker image to GitHub Container Registry
          uses: docker/build-push-action@v3
          with:
              push: true
              tags: ghcr.io/${{ env._username }}/${{ inputs.imagename }}:${{ inputs.tagname }}
