name: unit-test

on: workflow_dispatch

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${ OWNER,, }
                  password: ${{ secrets.GHCR_PAT }}
              env:
                  OWNER: ${{ github.repository_owner }}
            - name: Set up Docker
              run: |
                  docker pull ghcr.io/${ OWNER,, }/python-test-example:latest
                  docker-compose up -d
              env:
                  OWNER: ${{ github.repository_owner }}
            - name: test
              run: docker-compose exec -T app pytest --cov
